### ISSUE TITLE
Use of fork in Test::Module::Build::Pluggable

### ISSUE THREAD

**Issue by garfieldnate** [tokuhirom/Module-Build-Pluggable#2]
This bug involves three separate modules. I am unable to install Module::Build::Pluggable::CPANfile on Windows because the test script uses Capture::Tiny to check output from Test::Module::Build::Pluggable. This causes perl to crash. I filed [this](https://github.com/dagolden/capture-tiny/issues/12) for Capture::Tiny. It turns out that Perl crashes on Windows when you try to capture code that uses `fork`, which both `run_build_pl` and `run_build_script` in Test::Module::Build::Pluggable do. As David may be classifying the Capture::Tiny ticket as unfixable, I'm filing this ticket so that you know that module authors who try to capture stderr or stdout from your module will cause perl to crash (on Windows, at least).
Anyways, I think you may want to consider either 1) documenting the use of fork in this module or 2) not using fork. I don't understand the use of it in your module well enough to comment or provide a patch.
The last ticket I'm filing is with Module::Build::Pluggable::CPANfile. If your code keeps the `fork` calls, then his will have to remove the `capture_stderr` calls. https://rt.cpan.org/Ticket/Display.html?id=88304

**Comment by tokuhirom** [comment]
First, the code using fork(2) is not surprisingly thing.
@kazeburo I suggest to skip the test case on Win32 for now.
